### ISSUE TITLE
Is there any flag for enhanced skills by the Djinn's wishes and if so, does the program support it?

### ISSUE THREAD

**Issue by lwcorp** [Blazingstix/QFGImporter#6]
I believe in QFG2 skills aren't supposed go beyond 200 points unless they were enhanced by the Djinn's **two** wishes (whereas the third and last available wish must be a one time teleportation). 
I've also seen claims that it's enforced right before the export is created (in the final score menu any skills beyond 200 drop to 200 except for the two Djinn enhanced ones).

But as for SAV file itself, is there any flag for which **two** skills were enhanced? If so, the program doesn't seem to show it.
Instead it lets you enhance **all skills** beyond 200 (actually into 255) and indeed QFG3 accepts it:

![image](https://user-images.githubusercontent.com/1773306/79042878-fd9ea480-7c03-11ea-8ed3-b02d52eebd0f.png)

**Comment by Blazingstix** [comment]
There are no flags in the export file to indicate which skills were enhanced by wishes.  There may be some in the game itself -- I don't know -- but any in-game flags are completely irrelevant to the export file.

I agree that it's the intention to not go above 200 points (except for the wishes), but since the export file support up to 255, so does the program.
